name: Image Optimizer Action
# Define when to run job here
on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Runing Image Optimizer Action
    steps:
    - uses: actions/checkout@v2
    - uses: MarketingPipeline/Image-Optimizer-Action@main
        
     # Commit the updates
    - name: Commit and Push Optimized Images
      run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Added Optimized Image"
         git push
