#!/bin/bash

#####################################################
# Image Optimzer Action
# Created by github.com/MarketingPipeline
#####################################################

#!/bin/bash

#####################################################
#  Download Specific folders from Github using SVN
#  
#  Orginal Author: Declan Cook
#  Modified by: MarketingPip from github.com/MarketingPipeline
#  Licence: MIT
#####################################################
FILEPATH=$1
RECURSION=$2

### File Path Option
if [ -z "$FILEPATH" ]
then
      echo "\Image path or folder path was not specified, optimizing all image files in repo"
      FILEPATH="./"
else
      echo "\Image path or folder path was provided, $FILEPATH will be optimized if it exists"
      FILEPATH=$FILEPATH
fi


### Overwrite files

if [ -z "$RECURSION" ]
then
      echo "\RECURSION option was not chosen, optimizing all image files in $FILEPATH, without recursion"
      RECURSION="-nr"
else
      echo "\RECURSION option was chosen, optimizing all image files in $FILEPATH and all of its subdirectories "
      RECURSION=""
fi

optimize-images $RECURSION $FILEPATH

   
