#!/bin/bash

#####################################################
# Image Optimzer Action
# Created by github.com/MarketingPipeline
#####################################################

optimize-images ./

   
